<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!-- TODO -->
    <NoWarn>CS8602;CS8603;CS8604</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.Http\jaytwo.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="jaytwo.MimeHelper" Version="0.1.3" />
    <PackageReference Include="jaytwo.SolutionResolution" Version="0.1.1" />
    <PackageReference Include="MartinCostello.Logging.XUnit" Version="0.6.0" />
  </ItemGroup>

</Project>
